language: ruby
services:
  - postgresql
rvm:
- 2.5.0
before_install:
- bundle config build.nokogiri --use-system-libraries
bundler_args: "--without production"
before_script:
  - psql -c 'create database pmpsupport_test;' -U postgres
sudo: false
notifications:
  slack:
    secure: UWLKi9OO/NNPSmJnFYGzLTmwqZeym2fma5cInZV/Q8UyxPhIq58GA3nbtX5OgSozr0aX3ciVBrFIhz9Q14D6ynvVizHnXGm6lGOLqbKmp9JPMUTb4JDSEwNobi4uXcRV0c5WmOIun5W8Kl45zOIDkMVkH3wwhNUvFuJIdh3ZugI=